language: ruby

rvm:
  - 2.4.1

cache: bundler

services:
  - mysql
  - elasticsearch

before_script:
  - sleep 10 # To make sure Elasticsearch instance is ready

before_install:
  - mysql -e 'CREATE DATABASE webscale_test;'

notifications:
  email:
    on_success: never
    on_failure: always
